version: '3.6'
services:
  api:
    build:
      context: ./
      args:
        port: ${PORT:-3000}
    image: webhook_api_example_js:dev
    command: ["node", "server.js"]
    ports:
      - 3133:${PORT:-3000}
