version: '3.6'
services:
  api:
    build:
      context: ./
      args:
        port: ${PORT:-3000}
    image: webhook_api_example_py:dev
    command: ["python", "server.py"]
    environment:
      - HOST=0.0.0.0
    ports:
      - 3131:${PORT:-3000}
    volumes:
      - ./server.py:/usr/src/api/server.py
